---
title: "soc_imputations"
author: "Ashley Yang"
date: "2024-07-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries and loading}
library(opengender)
library(data.table)
library(dplyr)

data <-read.csv("/Users/ashleyyang/Desktop/RA/ror_data/v.1.49.csv")
soc <- readRDS("/Users/ashleyyang/Desktop/RA/sociology_dissertations_extract.RDS")

data <- data[order(data$name), ]
soc <- soc[order(soc$organization), ]

View(data)
View(soc)
```

```{r perfect match ror -- filter method}
##from the soc df, look into the data df, look for org name from soc in "name" column 
soc$ror_id <- NA

for (i in 1:nrow(soc)) {
  soc_org <- soc$organization[i]
  df_filtered <- filter(data, name == soc_org)
  df_filtered2 <- filter(data, aliases == soc_org)
  
  if (nrow(df_filtered) > 0) {
    soc$ror_id[i] <- df_filtered$id[1]
  ##if not in, look at alias column

  } else if (nrow(df_filtered2) > 0) {
    soc$ror_id[i] <- df_filtered2$id[1]
  } else{
    soc$ror_id[i] <- NA
  }
}

##if not in either bucket, go onto fuzzy matching 
```

```{r joining method}
##left join? need to understand... 
View(data)
##practice r syntax...
```

```{r normalization part 1}
library(stringr)
library(tidyverse)

soc_na <- filter(soc, is.na(ror_id))
as.data.frame(soc_na)

soc_na$ror_id <- NA

normalize_org_name <- function(name) {
  name <- str_remove_all(name, "\\(.*?\\)")  #anything in parentheses
  name <- str_remove(name, "^The\\s")  #"The" at the beginning
  name <- str_remove_all(name, ",")  #commas that dint need to be there
  name <- str_replace_all(name, "\\s*-\\s*", "-")  #extra spaces around hyphens
  name <- str_trim(name)  #exttra spaces
  name <- str_replace(name, "State University of New York", "SUNY")
  name <- str_squish(name)  #extra spaces within the text
  return(name)
}

#if Albany, would just be SUNY, not SUNY Albany
#'at' is sometimes the issue, but with U of Alabama, it is not, same with UNC 
#Rutgers... I do not know what to do about that


soc_na$normalized_org <- normalize_org_name(soc_na$organization)

soc_na <- soc_na %>%
  mutate(normalized_org = trimws(normalized_org))
  
data_expanded <- data %>%
  separate_rows(aliases, sep = ";") %>%
  mutate(aliases = trimws(aliases)) #whitespaces after the ;

#joining basesd on names
soc_na_joined <- soc_na %>%
  left_join(data_expanded, by = c("normalized_org" = "name")) %>%
  mutate(ror_id = id.y) %>%
  select(normalized_org, ror_id)

#join from alias (data expanded from above)
soc_na_joined2 <- soc_na %>%
  left_join(data_expanded, by = c("normalized_org" = "aliases")) %>%
  mutate(ror_id = id.y) %>%
  select(normalized_org, ror_id)

#merging the two, but just want non-na values (coalesce?)
combined_result <- soc_na_joined %>%
  full_join(soc_na_joined2, by = "normalized_org", suffix = c(".name", ".aliases")) %>%
  mutate(ror_id = coalesce(ror_id.name, ror_id.aliases)) %>%
  select(normalized_org, ror_id)

View(combined_result)

df_na <- filter(combined_result, is.na(combined_result$ror_id))
View(df_na)

print(unique(df_na_2$normalized_org))

```

```{r fuzzy matching}
library(fuzzyjoin)
#rename df_na_2 "organization" to "name"
colnames(df_na_2)
df_na_unique <- df_na_2[!duplicated(df_na_2[,c('normalized_org')]),]
View(df_na_unique)

matched_part1 <- stringdist_left_join(df_na_unique, data, by = c(normalized_org = "name"), distance_col = "dist")
matched_part2 <-  stringdist_left_join(df_na_unique, data_expanded, by = c(normalized_org = "aliases"), distance_col = "dist")
View(matched_part1)

fuzzy_joined_results <- matched_part1 %>%
  full_join(matched_part2, by = "normalized_org", suffix = c(".name", ".aliases")) %>% 
  mutate(ror_id = coalesce(id.name, id.aliases)) %>% #coalesce = prioitize the value that is not NA 
  select(normalized_org, ror_id)
#The fuzzy joined results
View(fuzzy_joined_results)
```

```{ r notes}
#Open University... Not a success
#UNC Chapel Hill, why?
#

```
